### ISSUE TITLE
Getting "Possible Unhandled Promise Rejection" with try/catch around request hook call

### ISSUE THREAD

**Issue by laurenzcodes** [reduxjs/redux-toolkit#2986]
I have the following endpoint which returns a json if the response code is 200 and a plain/text when its 404 saying `Current working hours not available for...`

```ts
    /* 200: current working time information returned in body
    /* 404: no current working time information available for authenticated user
    */
    workingTimeCurrent: builder.mutation<ITimeTrackingState, void>({
      query: () => ({
        url: `/v1/working-time/current`,
        method: 'GET',
      }),
      transformResponse: transformWorkingTimeResponse,
      extraOptions: {

      },
      async onQueryStarted(_, { queryFulfilled }) {
        try {
          const { data } = await queryFulfilled
          log('workingTimeCurrent_query_success', data)
        } catch (err: any) {
          log('workingTimeCurrent_query_failed', err)

        }
      },
    })
```

I consume the hook which comes from this endpoint using this function

```ts
  const [getCurrentWorkingTime] = useWorkingTimeCurrentMutation();
  const refetchCurrentWorkingTime = async () => {
    try {
      const currentWorkingTimeData = await getCurrentWorkingTime().unwrap();
      dispatch(refreshCurrentTimeTracking(currentWorkingTimeData));
    } catch (error) {
      // If the response is 404 there currently is no tracked shift
      if ((error as { originalStatus: number }).originalStatus === 404) {
        dispatch(
          refreshCurrentTimeTracking({
            hasNotStarted: true,
            cachedQueryTimestamp: moment().toISOString(),
            hasStarted: false,
            hasStopped: false,
            timestampStart: null,
            planItemID: null,
          })
        );
      }
    }
  };
```

This works as it should, however I get a warning when the response is 404 saying
`Possible Unhandled Promise Rejection (SyntaxError: JSON Parse error: Unexpected token: C)`
where the `C` is the first letter of the "Current.." in the text response. The issue is somewhere in the `getCurrentWorkingTime()` query call, I've tried removing all the code around it and the warning persists.

Question is, why is it complaining about an unhandled promise even though I am handling the error case in my `try/catch`?
Not sure if this is an issue with Redux rtk query or in my code but I would appreciate any help I can get.

**Comment by laurenzcodes** [comment]
Is there any other solutions I can implement on the front end that do not require me to talk to the backend guys to change the response type?

**Comment by markerikson** [comment]
You could supply a custom `responseHandler` and do the "JSON or text" handling yourself:

- https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#parsing-a-response

**Comment by phryneas** [comment]
If the server returns the data with a correct header, you can set `responseHandler: 'content-type'`.

But generally, your server should really have a consistent response. Maybe you just need to set an `Accept` header and then you get a JSON error from the server? If not, that should be fixed on the server.

**Comment by laurenzcodes** [comment]
I know this issue is closed already, but I still have the problem after implementing the responseHandler.

This is my changed code

```workingTimeCurrent: builder.mutation<ITimeTrackingState, void>({
      query: () => ({
        url: `/v1/working-time/current`,
        method: 'GET',
        responseHandler: async (response) => {
          if (response.headers.get('Content-Type')?.includes('text/plain')) {
            return response.text();
          }
          return response.json();
        },
      }),
      transformResponse: transformWorkingTimeResponse,
      extraOptions: {},
      async onQueryStarted(_, { queryFulfilled }) {
        try {
          const { data } = await queryFulfilled;
          log('workingTimeCurrent_query_success', data);
        } catch (err: any) {
          log('workingTimeCurrent_query_failed', err);
        }
      },
    }),
```

The warning pops up anyway and it's seemingly impossible to trace back from where this is coming.
Any more help I could get would be appreciated.

**Comment by phryneas** [comment]
I would assume that your `transformWorkingTimeResponse` is throwing an exception.
