### ISSUE TITLE
Consider adding a warning if default middlewares run too slow

### ISSUE THREAD

**Issue by matthieudumas** [reduxjs/redux-toolkit#412]
I've switched to redux toolkit for a new project built with create react app, and encountered a big performance issue during development. Long story short, I was storing large amounts of json in the store and redux toolkit's default dev middlewares (redux-immutable-state-invariant and serializable-state-invariant-middleware) were taking around 400ms to validate each dispatch...

I'm an experienced react/redux developer, yet I didn't know about those middlewares. Chrome profiler didn't prove very useful, and it took me about 2 hours to nail down the problem.

I suspect other people might have the same problem than me. So what would you think about those middlewares to implement a self timer and raise a warning in the console if they take more than a certain time to run (eg 50ms, ie 20 FPS) ?

**Comment by markerikson** [comment]
Yeah, that seems like a reasonable thing to do.

Can you go ahead and file a PR against the `v1.3.0-integration` branch to add that?

**Comment by markerikson** [comment]
Done in 1.3.

**Comment by LuisGarcia9000** [comment]
> I've switched to redux toolkit for a new project built with create react app, and encountered a big performance issue during development. Long story short, I was storing large amounts of json in the store and redux toolkit's default dev middlewares (redux-immutable-state-invariant and serializable-state-invariant-middleware) were taking around 400ms to validate each dispatch...
> 
> I'm an experienced react/redux developer, yet I didn't know about those middlewares. Chrome profiler didn't prove very useful, and it took me about 2 hours to nail down the problem.
> 
> I suspect other people might have the same problem than me. So what would you think about those middlewares to implement a self timer and raise a warning in the console if they take more than a certain time to run (eg 50ms, ie 20 FPS) ?

@matthieudumas I have the same problem, How do you solved it?

**Comment by markerikson** [comment]
@LuisGarcia9000 The dev check middlewares have done that for the last year or so.  Also, we recently updated the middlewares in 1.5.x to run _much_ faster in most cases. Please make sure you are using the latest version of RTK (1.6.2+)

**Comment by LuisGarcia9000** [comment]
@markerikson I have updated to RTK 1.6.2, but the problem still remains, even though I have placed:
```
middleware: getDefaultMiddleware => [
    ...getDefaultMiddleware({
      immutableCheck: false,
      serializableCheck: false
    })
```
¿any siggestion?

**Comment by phryneas** [comment]
You might also want to try `immutableCheck: false`

**Comment by markerikson** [comment]
@LuisGarcia9000 : can you clarify what actual error you're seeing? You haven't shown any details yet.

**Comment by LuisGarcia9000** [comment]
My probles is this: dispatch this action si too slow, near 4 seg, I only are saving 4 addressess:
![image](https://user-images.githubusercontent.com/49536502/140552831-ca0e073c-cae4-486e-9aa5-419c75d0a065.png)

**Comment by markerikson** [comment]
@LuisGarcia9000 Hmm. There's no way that a basic dispatch should be taking 4 seconds, and I strongly doubt that the dev check middleware are the problem here.

Can you please post a repository or CodeSandbox that shows the problem actually happening? It's likely that there's some other problem going on in the app, but I can't say what might be the cause without seeing the actual code.

**Comment by LuisGarcia9000** [comment]
@markerikson ok, I'm going to looking for in another place, maybe my configuration.
Thank you very much.

**Comment by phryneas** [comment]
@LuisGarcia9000 configuration would also not be the issue here. Is this maybe an api call that just answers after four seconds?

**Comment by LuisGarcia9000** [comment]
> @LuisGarcia9000 configuration would also not be the issue here. Is this maybe an api call that just answers after four seconds?

@phryneas I don´t know where is the problem but this is only happen on "development", apk is working very fast.
